name: PHP CI/CD to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: my-php-app   # Replace with your Azure Web App name
  AZURE_CONTAINER_REGISTRY: myacr.azurecr.io  # Replace with your Azure Container Registry URL
  IMAGE_NAME: php-app

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        working-directory: src

      - name: Run PHP Lint
        run: find src -type f -name "*.php" -exec php -l {} \;

      - name: Run Tests
        run: vendor/bin/phpunit
        working-directory: src

  build-and-deploy:
    name: Build & Deploy to Azure
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login $AZURE_CONTAINER_REGISTRY -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker Image to ACR
        run: docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
